### ISSUE TITLE
Cannot run `python setup.py`

### ISSUE THREAD

**Issue by dhruvghulati** [misja/python-boilerpipe#36]
I am using Anaconda on 2.7 python version.

I tried also `pip install setup.py` after reading this:

http://stackoverflow.com/questions/8295644/pypi-userwarning-unknown-distribution-option-install-requires

But got:

`Could not find a version that satisfies the requirement setup.py (from versions: )
No matching distribution found for setup.py`

**Comment by najeebta** [comment]
I was also not able to install, then I tried with this:
pip install JPype1
pip install charade
git clone https://github.com/misja/python-boilerpipe.git
cd python-boilerpipe
sudo python setup.py install

This was throwing an error of gzip thing.
The issue was in the setup.py they looks for a file from goole code and its not there any more. So just edit the setup.py and give the file location as tgz_url='https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/boilerpipe/boilerpipe-1.2.0-bin.tar.gz' 

This worked for me

**Comment by tuxdna** [comment]
Fixed in this PR - https://github.com/misja/python-boilerpipe/pull/38
